#!/bin/bash

check_input_range() {
  local flag=0
  local REGEX="^[1-6]?$"
  local count=1
  for arg in "$@";do
    if ! [[ $arg =~ $REGEX ]] || [ $count == 5 ];then
      flag=1
      break
    fi
    ((count++))
  done
  return $flag
}

get_color_font() {
  case "$1" in
  1) echo "\e[97m";;
  2) echo "\e[31m";;
  3) echo "\e[32m";;
  4) echo "\e[34m";;
  5) echo "\e[35m";;
  6) echo "\e[30m";;
  esac
}

get_color_background() {
  case "$1" in
  1) echo "\e[107m";;
  2) echo "\e[41m";;
  3) echo "\e[42m";;
  4) echo "\e[44m";;
  5) echo "\e[45m";;
  6) echo "\e[40m";;
  esac
}

print_all() {
  
  local	P1=$(get_color_background $1)$(get_color_font $2)
  local	P2=$(get_color_background $3)$(get_color_font $4)  
  local END="\e[0m"

  echo -e "${P1}HOSTNAME =${END}${P2} $HOSTNAME${END}"
  echo -e "${P1}TIMEZONE =${END}${P2} $(cat /etc/timezone)${END}"
  echo -e "${P1}USER =${END}${P2} $USER${END}"
  echo -e "${P1}OS =${END}${P2} $OSTYPE${END}"
  echo -e "${P1}DATE =${END}${P2} $(date +%d) $(date +%b) $(date +%Y) $(date +%H:%M:%S)${END}"
  echo -e "${P1}UPTIME =${END}${P2} $(uptime -p)${END}"
  echo -e "${P1}UPTIME_SEC =${END}${P2} $(awk '{print $1}' /proc/uptime)${END}"
  echo -e "${P1}IP =${END}${P2} $(hostname -I)${END}"
  echo -e "${P1}MASK =${END}${P2} $(ifconfig | grep netmask | sed -n 1p | awk '{print $4}')${END}"
  echo -e "${P1}GATEWAY =${END}${P2} $(ip r | grep default | awk '{print $3}')${END}"
  echo -e "${P1}RAM_TOTAL =${END}${P2} `echo "scale=3; $(free -m | grep Mem | awk '{print $2}') / 1024.0" | bc` GB${END}"
  echo -e "${P1}RAM_USED =${END}${P2} `echo "scale=3; $(free -m | grep Mem | awk '{print $3}') / 1024.0" | bc` GB${END}"
  echo -e "${P1}RAM_FREE =${END}${P2} `echo "scale=3; $(free -m | grep Mem | awk '{print $4}') / 1024.0" | bc` GB${END}"
  echo -e "${P1}SPACE_ROOT =${END}${P2} `echo "scale=2; $(df / | grep dev | awk '{print $2}') / 1024.0" | bc` MB${END}"
  echo -e "${P1}SPACE_ROOT_USED =${END}${P2} `echo "scale=2; $(df / | grep dev | awk '{print $3}') / 1024.0" | bc` MB${END}"
  echo -e "${P1}SPACE_ROOT_FREE =${END}${P2} `echo "scale=2; $(df / | grep dev | awk '{print $4}') / 1024.0" | bc` MB${END}"
}
