#!/bin/bash
  
check_input() {
  if [ $# -lt 1 ]; then
    echo "Wrong less than 1 arguments!"
    exit 1
  fi
  if [ $# -gt 1 ]; then
    echo "Wrong greater than 1 arguments!"
    exit 1
  fi
  if [[ ! $1 =~ ^[1-3]{1}$ ]]; then
    echo "Wrong in 1 arguments!"
    exit 1
  fi
  echo "Script run"
}

mode() {
  if [ $1 == 1 ]; then
    first_task
  elif [ $1 == 2 ]; then
    second_task
  elif [ $1 == 3 ]; then
    third_task    
  fi
  echo "Finish script"
}

first_task() {
  REGEX="(,){1}\s([0-9]{1,2}\.){2}[0-9]{4}$"
  read -p "Введите абсолютный путь к файлу file.log: " file
  for line in $( grep -E $REGEX $file | awk '{print $1}'); do
  line=${line%?}
  rm -rf $line
  done
  rm -rf $file
}

# 2023-06-11 12:06:00
# 2023-11-01 02:56:00
second_task() {
  read -p "Введите дату и время начала промежутка (YYYY-MM-DD HH:MM:SS): " start_date
  read -p "Введите дату и время конец промежутка (YYYY-MM-DD HH:MM:SS): " finish_date
  read -p "Введите директорию для поиска: " way
  REGEX="^[0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2}$"
  if [[ $start_date =~ $REGEX ]] && [[ $finish_date =~ $REGEX ]]; then
    start_time=$(date -d "$start_date" +%s)
    finish_time=$(date -d "$finish_date" +%s)
    if [ -z $start_time ] || [ -z $finish_time ] || [ $start_time -ge $finish_time ]; then
      echo "Wrong input date!"
      exit 1
    elif [ ! -d $way ]; then 
      echo "Directory "$way" does not exist!"
      exit 1
    fi
    find $way -newermt "$start_date" \! -newermt "$finish_date" -exec rm -rf {} \; 2>/dev/null
  else 
    echo "Wrong input!"
    exit 1
  fi
}

third_task() {
  read -p "Введите маску имени (т.е. символы, нижнее подчёркивание и дату): " line
  read -p "Введите директорию для поиска: " way
  if [ -z $line ]; then
    echo "Wrong input date!"
    exit 1
  elif [ ! -d $way ]; then 
    echo "Directory "$way" does not exist!"
    exit 1
  fi
  mask=$(echo $line | cut -f1 -d_)
  date=$(echo $line | cut -f2 -d_)
  REGEX="^$way\/$mask[A-Za-z0-9]*_$date$"
  find $way -regex $REGEX -exec rm -rf {} \; 2>/dev/null
}