/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "unitTests.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#include "s21_math.h"
#define PRECISION 1e-6

START_TEST(s21_abs1) {
  int test1 = 5;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs2) {
  int test1 = -5;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs3) {
  int test1 = 0;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs4) {
  int test1 = 2147483647;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs5) {
  int test1 = -2147483647;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs6) {
  int test1 = -49879879;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs7) {
  int test1 = -2147483648;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs8) {
  int test1 = -0xA13;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_abs9) {
  int test1 = -00002345670;
  ck_assert_int_eq(abs(test1), s21_abs(test1));
}
END_TEST

START_TEST(s21_fabs1) {
  double test1 = 1000.56;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs2) {
  double test1 = -1000.56;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs3) {
  double test1 = 0.0;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs4) {
  double test1 = 1.79769e+308;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs5) {
  double test1 = -1.79769e+308;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs6) {
  double test1 = -1.0 / 0.0;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs7) {
  double test1 = 1.0 / 0.0;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs8) {
  double test1 = -0.0;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_fabs9) {
  double test1 = -1.000005;
  ck_assert_ldouble_eq(fabsl(test1), s21_fabs(test1));
}
END_TEST

START_TEST(s21_floor1) {
  double test1 = 2000.56431;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor2) {
  double test1 = -2000.561351;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor3) {
  double test1 = 0.0;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor4) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor5) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor6) {
  double test1 = -0.532568;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor7) {
  double test1 = 1.532568;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_floor8) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_floor(test1));
}
END_TEST

START_TEST(s21_floor9) {
  double test1 = -4.7323234567890765;
  ck_assert_ldouble_eq(floorl(test1), s21_floor(test1));
}
END_TEST

START_TEST(s21_ceil1) {
  double test1 = 245484.56431;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil2) {
  double test1 = -24894486.561351;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil3) {
  double test1 = 0.0;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil4) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil5) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil6) {
  double test1 = -0.532568;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil7) {
  double test1 = 1.532568;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil8) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_floor(test1));
}
END_TEST

START_TEST(s21_ceil9) {
  double test1 = -4732323456789076.5;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil10) {
  double test1 = -4.7323234567890765;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil11) {
  double test1 = 4732323456789076.5;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_ceil12) {
  double test1 = 4.7323234567890765;
  ck_assert_ldouble_eq(ceill(test1), s21_ceil(test1));
}
END_TEST

START_TEST(s21_fmod1) {
  double test1 = 25315435.55;
  double test2 = 5425615.78;
  ck_assert_ldouble_eq(fmodl(test1, test2), s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod2) {
  double test1 = 2135153.561351;
  double test2 = 0;
  ck_assert_ldouble_nan(s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod3) {
  double test1 = 0.0;
  double test2 = 5655.56431;
  ck_assert_ldouble_eq(fmodl(test1, test2), s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod4) {
  double test1 = S21_POSINF;
  double test2 = 21554615.56431;
  ck_assert_ldouble_nan(s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod5) {
  double test1 = S21_NEGINF;
  double test2 = 1.79769e+1;
  ck_assert_ldouble_nan(s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod6) {
  double test1 = -0.532568;
  double test2 = S21_POSINF;
  ck_assert_ldouble_eq(fmodl(test1, test2), s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod7) {
  double test1 = 1.532568;
  double test2 = S21_NEGINF;
  ck_assert_ldouble_eq(fmodl(test1, test2), s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod8) {
  double test1 = S21_NAN;
  double test2 = 12.6;
  ck_assert_ldouble_nan(s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_fmod9) {
  double test1 = 12.6;
  double test2 = S21_NAN;
  ck_assert_ldouble_nan(s21_fmod(test1, test2));
}
END_TEST

START_TEST(s21_exp1) {
  double test1 = 15;
  ck_assert_ldouble_eq_tol(expl(test1), s21_exp(test1), PRECISION);
}
END_TEST

START_TEST(s21_exp2) {
  double test1 = 9898989999999.1556;
  ck_assert_ldouble_eq(expl(test1), s21_exp(test1));
}
END_TEST

START_TEST(s21_exp3) {
  double test1 = 0.0;
  ck_assert_ldouble_eq_tol(expl(test1), s21_exp(test1), PRECISION);
}
END_TEST

START_TEST(s21_exp4) {
  double test1 = 20.551;
  ck_assert_ldouble_eq_tol(expl(test1), s21_exp(test1), PRECISION);
}
END_TEST

START_TEST(s21_exp5) {
  double test1 = -20;
  ck_assert_ldouble_eq_tol(expl(test1), s21_exp(test1), PRECISION);
}
END_TEST

START_TEST(s21_exp6) {
  double test1 = -0.53257;
  ck_assert_ldouble_eq_tol(expl(test1), s21_exp(test1), PRECISION);
}
END_TEST

START_TEST(s21_exp7) {
  double test1 = 1.2789;
  ck_assert_ldouble_eq_tol(expl(test1), s21_exp(test1), PRECISION);
}
END_TEST

START_TEST(s21_exp8) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_eq(exp(test1), s21_exp(test1));
}
END_TEST

START_TEST(s21_exp9) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_eq(exp(test1), s21_exp(test1));
}
END_TEST

START_TEST(s21_exp10) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_exp(test1));
}
END_TEST

START_TEST(s21_exp11) {
  double test1 = S21_LDMAX;
  ck_assert_ldouble_eq(exp(test1), s21_exp(test1));
}
END_TEST

START_TEST(s21_exp12) {
  double test1 = S21_LDMIN;
  ck_assert_ldouble_eq(exp(test1), s21_exp(test1));
}
END_TEST

START_TEST(s21_pow1) {
  double test1 = 0.0;
  double test2 = 0.0;
  ck_assert_ldouble_eq_tol(pow(test1, test2), s21_pow(test1, test2), PRECISION);
}
END_TEST

START_TEST(s21_pow2) {
  double test1 = 0.0;
  double test2 = 15.0;
  ck_assert_ldouble_eq_tol(pow(test1, test2), s21_pow(test1, test2), PRECISION);
}
END_TEST

START_TEST(s21_pow3) {
  double test1[] = {1.12, -34.45, S21_NAN, -S21_NAN, S21_POSINF, S21_NEGINF};
  double test2 = 0.0;
  int i = _i;
  ck_assert_ldouble_eq_tol(pow(test1[i], test2), s21_pow(test1[i], test2),
                           PRECISION);
}
END_TEST

START_TEST(s21_pow4) {
  double test1 = -5;
  double test2 = 28.1;
  ck_assert_ldouble_nan(s21_pow(test1, test2));
}
END_TEST

START_TEST(s21_pow5) {
  double test1 = -6;
  double test2 = -1.65;
  ck_assert_ldouble_nan(s21_pow(test1, test2));
}
END_TEST

START_TEST(s21_pow6) {
  double test1 = 8;
  double test2 = -2.69;
  ck_assert_ldouble_eq_tol(pow(test1, test2), s21_pow(test1, test2), PRECISION);
}
END_TEST

START_TEST(s21_pow7) {
  double test1 = 23549;
  double test2 = 3;
  ck_assert_ldouble_eq_tol(pow(test1, test2), s21_pow(test1, test2), PRECISION);
}
END_TEST

START_TEST(s21_pow8) {
  double test1 = 0.0;
  double test2 = -10.5;
  ck_assert_ldouble_eq(pow(test1, test2), s21_pow(test1, test2));
}
END_TEST

START_TEST(s21_pow9) {
  double test1 = 1.0;
  double test2[] = {1, 1.23, -1.23, S21_NAN, -S21_NAN, S21_POSINF, S21_NEGINF};
  int i = _i;
  ck_assert_ldouble_eq_tol(pow(test1, test2[i]), s21_pow(test1, test2[i]),
                           PRECISION);
}
END_TEST

START_TEST(s21_pow10) {
  double test1[] = {1.12, -34.45, S21_NAN, -S21_NAN, S21_POSINF, S21_NEGINF};
  double test2 = S21_NAN;
  int i = _i;
  ck_assert_ldouble_nan(s21_pow(test1[i], test2));
}
END_TEST

START_TEST(s21_pow11) {
  double test1 = S21_NAN;
  double test2[] = {1, 1.23, -1.23, S21_NAN, -S21_NAN, S21_POSINF, S21_NEGINF};
  int i = _i;
  ck_assert_ldouble_nan(s21_pow(test1, test2[i]));
}
END_TEST

START_TEST(s21_pow12) {
  double test1 = S21_LDMAX;
  double test2 = -10;
  ck_assert_ldouble_eq_tol(pow(test1, test2), s21_pow(test1, test2), PRECISION);
}
END_TEST

START_TEST(s21_pow13) {
  double test1 = S21_LDMIN;
  double test2 = 10;
  ck_assert_ldouble_eq(pow(test1, test2), s21_pow(test1, test2));
}
END_TEST

START_TEST(s21_log1) {
  double test1 = 0.0;
  ck_assert_ldouble_eq(log(test1), s21_log(test1));
}
END_TEST

START_TEST(s21_log2) {
  double test1 = -0.61;
  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_log3) {
  double test1 = 0.78;
  ck_assert_ldouble_eq_tol(log(test1), s21_log(test1), PRECISION);
}
END_TEST

START_TEST(s21_log4) {
  double test1 = 10.2;
  ck_assert_ldouble_eq_tol(log(test1), s21_log(test1), PRECISION);
}
END_TEST

START_TEST(s21_log5) {
  double test1 = -6.8;
  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_log6) {
  double test1 = 1561.15;
  ck_assert_ldouble_eq_tol(log(test1), s21_log(test1), PRECISION);
}
END_TEST

START_TEST(s21_log7) {
  double test1 = -265.899;
  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_log8) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_eq(log(test1), s21_log(test1));
}
END_TEST

START_TEST(s21_log9) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_log10) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_log11) {
  double test1 = -S21_NAN;
  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_log12) {
  double test1 = S21_LDMAX;
  ck_assert_ldouble_eq_tol(log(test1), s21_log(test1), PRECISION);
}
END_TEST

START_TEST(s21_log13) {
  double test1 = S21_LDMIN;

  ck_assert_ldouble_nan(s21_log(test1));
}
END_TEST

START_TEST(s21_sqrt1) {
  double test1 = 0.0;
  ck_assert_ldouble_eq_tol(sqrt(test1), s21_sqrt(test1), PRECISION);
}
END_TEST

START_TEST(s21_sqrt2) {
  double test1 = -100;
  ck_assert_ldouble_nan(s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt3) {
  double test1 = 100;
  ck_assert_ldouble_eq_tol(sqrt(test1), s21_sqrt(test1), PRECISION);
}
END_TEST

START_TEST(s21_sqrt4) {
  double test1 = 25000.25;
  ck_assert_ldouble_eq_tol(sqrt(test1), s21_sqrt(test1), PRECISION);
}
END_TEST

START_TEST(s21_sqrt5) {
  double test1 = -1;
  ck_assert_ldouble_nan(s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt6) {
  double test1 = 0.1;
  ck_assert_ldouble_eq_tol(sqrt(test1), s21_sqrt(test1), PRECISION);
}
END_TEST

START_TEST(s21_sqrt7) {
  double test1 = -0.1;
  ck_assert_ldouble_nan(s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt8) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_eq(sqrt(test1), s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt9) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_nan(s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt10) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt11) {
  double test1 = S21_PI;
  ck_assert_ldouble_eq_tol(sqrt(test1), s21_sqrt(test1), PRECISION);
}
END_TEST

START_TEST(s21_sqrt12) {
  double test1 = S21_LDMIN;
  ck_assert_ldouble_nan(s21_sqrt(test1));
}
END_TEST

START_TEST(s21_sqrt13) {
  double test1 = 1e-7;
  ck_assert_ldouble_eq_tol(sqrt(test1), s21_sqrt(test1), PRECISION);
}
END_TEST

START_TEST(s21_sin1) {
  double test1 = 2.523;
  ck_assert_ldouble_eq_tol(sin(test1), s21_sin(test1), PRECISION);
}
END_TEST

START_TEST(s21_sin2) {
  double test1 = -2.523;
  ck_assert_ldouble_eq_tol(sin(test1), s21_sin(test1), PRECISION);
}
END_TEST

START_TEST(s21_sin3) {
  double test1 = 923456789;
  ck_assert_ldouble_eq_tol(sin(test1), s21_sin(test1), PRECISION);
}
END_TEST

START_TEST(s21_sin4) {
  double test1 = -923456789;
  ck_assert_ldouble_eq_tol(sin(test1), s21_sin(test1), PRECISION);
}
END_TEST

START_TEST(s21_sin5) {
  double test1 = 0;
  ck_assert_ldouble_eq_tol(sin(test1), s21_sin(test1), PRECISION);
}
END_TEST

START_TEST(s21_sin6) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_sin(test1));
}
END_TEST

START_TEST(s21_sin7) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_nan(s21_sin(test1));
}
END_TEST

START_TEST(s21_sin8) {
  double test1 = 0.12345678901234567890;
  ck_assert_ldouble_eq_tol(sin(test1), s21_sin(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos1) {
  double test1 = 0.4;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos2) {
  double test1 = -0.4;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos3) {
  double test1 = 0;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos4) {
  double test1 = 1;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos5) {
  double test1 = -1;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos6) {
  double test1 = S21_PI;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos7) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_cos(test1));
}
END_TEST

START_TEST(s21_cos8) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_nan(s21_cos(test1));
}
END_TEST

START_TEST(s21_cos9) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_nan(s21_cos(test1));
}
END_TEST

START_TEST(s21_cos10) {
  double test1 = -923456789;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_cos11) {
  double test1 = -2.523;
  ck_assert_ldouble_eq_tol(cos(test1), s21_cos(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan1) {
  double test1 = 0.4;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan2) {
  double test1 = -0.4;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan3) {
  double test1 = 0;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan4) {
  double test1 = 1;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan5) {
  double test1 = -1;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan6) {
  double test1 = 400000.23;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan7) {
  double test1 = -400000.23;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan8) {
  double test1 = 0.123456789012345678901234567890;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan9) {
  double test1 = S21_PI;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan10) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_tan(test1));
}
END_TEST

START_TEST(s21_tan11) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_nan(s21_tan(test1));
}
END_TEST

START_TEST(s21_tan12) {
  double test1 = S21_NEGINF;
  ck_assert_ldouble_nan(s21_tan(test1));
}
END_TEST

START_TEST(s21_tan13) {
  double test1 = 1 + 1e-6;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_tan14) {
  double test1 = -1 - 1e-6;
  ck_assert_ldouble_eq_tol(tan(test1), s21_tan(test1), PRECISION);
}
END_TEST

START_TEST(s21_asin1) {
  double test1 = -0.4;
  ck_assert_ldouble_eq_tol(asin(test1), s21_asin(test1), PRECISION);
}
END_TEST

START_TEST(s21_asin2) {
  double test1 = 0.4;
  ck_assert_ldouble_eq_tol(asin(test1), s21_asin(test1), PRECISION);
}
END_TEST

START_TEST(s21_asin3) {
  double test1 = 0.0;
  ck_assert_ldouble_eq_tol(asin(test1), s21_asin(test1), PRECISION);
}
END_TEST

START_TEST(s21_asin4) {
  double test1 = -0.0;
  ck_assert_ldouble_eq_tol(asin(test1), s21_asin(test1), PRECISION);
}
END_TEST

START_TEST(s21_asin5) {
  double test1 = -1;
  ck_assert_ldouble_eq_tol(asin(test1), s21_asin(test1), PRECISION);
}
END_TEST

START_TEST(s21_asin6) {
  double test1 = -5;
  ck_assert_ldouble_nan(s21_asin(test1));
}
END_TEST

START_TEST(s21_asin7) {
  double test1 = 5;
  ck_assert_ldouble_nan(s21_asin(test1));
}
END_TEST

START_TEST(s21_asin8) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_asin(test1));
}
END_TEST

START_TEST(s21_asin9) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_nan(s21_asin(test1));
}
END_TEST

START_TEST(s21_asin10) {
  double test1 = 0.123456789012345678901234567890;
  ck_assert_ldouble_eq_tol(asin(test1), s21_asin(test1), PRECISION);
}
END_TEST

START_TEST(s21_acos1) {
  double test1 = 2.523;
  ck_assert_ldouble_nan(s21_acos(test1));
}
END_TEST

START_TEST(s21_acos2) {
  double test1 = -2.523;
  ck_assert_ldouble_nan(s21_acos(test1));
}
END_TEST

START_TEST(s21_acos3) {
  double test1 = 923456789;
  ck_assert_ldouble_nan(s21_acos(test1));
}
END_TEST

START_TEST(s21_acos4) {
  double test1 = -923456789;
  ck_assert_ldouble_nan(s21_acos(test1));
}
END_TEST

START_TEST(s21_acos5) {
  double test1 = 0;
  ck_assert_ldouble_eq_tol(acos(test1), s21_acos(test1), PRECISION);
}
END_TEST

START_TEST(s21_acos6) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_acos(test1));
}
END_TEST

START_TEST(s21_acos7) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_nan(s21_acos(test1));
}
END_TEST

START_TEST(s21_acos8) {
  double test1 = 0.12345678901234567890;
  ck_assert_ldouble_eq_tol(acos(test1), s21_acos(test1), PRECISION);
}
END_TEST

START_TEST(s21_acos9) {
  double test1 = -0.68464861;
  ck_assert_ldouble_eq_tol(acos(test1), s21_acos(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan1) {
  double test1 = 2.523;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan2) {
  double test1 = -2.523;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan3) {
  double test1 = 923456789;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan4) {
  double test1 = -923456789;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan5) {
  double test1 = 0;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan6) {
  double test1 = S21_NAN;
  ck_assert_ldouble_nan(s21_atan(test1));
}
END_TEST

START_TEST(s21_atan7) {
  double test1 = S21_POSINF;
  ck_assert_ldouble_nan(s21_atan(test1));
}
END_TEST

START_TEST(s21_atan8) {
  double test1 = 0.12345678901234567890;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

START_TEST(s21_atan9) {
  double test1 = -0.68464861;
  ck_assert_ldouble_eq_tol(atan(test1), s21_atan(test1), PRECISION);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, s21_abs1);
  tcase_add_test(tc1_1, s21_abs2);
  tcase_add_test(tc1_1, s21_abs3);
  tcase_add_test(tc1_1, s21_abs4);
  tcase_add_test(tc1_1, s21_abs5);
  tcase_add_test(tc1_1, s21_abs6);
  tcase_add_test(tc1_1, s21_abs7);
  tcase_add_test(tc1_1, s21_abs8);
  tcase_add_test(tc1_1, s21_abs9);
  tcase_add_test(tc1_1, s21_fabs1);
  tcase_add_test(tc1_1, s21_fabs2);
  tcase_add_test(tc1_1, s21_fabs3);
  tcase_add_test(tc1_1, s21_fabs4);
  tcase_add_test(tc1_1, s21_fabs5);
  tcase_add_test(tc1_1, s21_fabs6);
  tcase_add_test(tc1_1, s21_fabs7);
  tcase_add_test(tc1_1, s21_fabs8);
  tcase_add_test(tc1_1, s21_fabs9);
  tcase_add_test(tc1_1, s21_floor1);
  tcase_add_test(tc1_1, s21_floor2);
  tcase_add_test(tc1_1, s21_floor3);
  tcase_add_test(tc1_1, s21_floor4);
  tcase_add_test(tc1_1, s21_floor5);
  tcase_add_test(tc1_1, s21_floor6);
  tcase_add_test(tc1_1, s21_floor7);
  tcase_add_test(tc1_1, s21_floor8);
  tcase_add_test(tc1_1, s21_floor9);
  tcase_add_test(tc1_1, s21_ceil1);
  tcase_add_test(tc1_1, s21_ceil2);
  tcase_add_test(tc1_1, s21_ceil3);
  tcase_add_test(tc1_1, s21_ceil4);
  tcase_add_test(tc1_1, s21_ceil5);
  tcase_add_test(tc1_1, s21_ceil6);
  tcase_add_test(tc1_1, s21_ceil7);
  tcase_add_test(tc1_1, s21_ceil8);
  tcase_add_test(tc1_1, s21_ceil9);
  tcase_add_test(tc1_1, s21_ceil10);
  tcase_add_test(tc1_1, s21_ceil11);
  tcase_add_test(tc1_1, s21_ceil12);
  tcase_add_test(tc1_1, s21_fmod1);
  tcase_add_test(tc1_1, s21_fmod2);
  tcase_add_test(tc1_1, s21_fmod3);
  tcase_add_test(tc1_1, s21_fmod4);
  tcase_add_test(tc1_1, s21_fmod5);
  tcase_add_test(tc1_1, s21_fmod6);
  tcase_add_test(tc1_1, s21_fmod7);
  tcase_add_test(tc1_1, s21_fmod8);
  tcase_add_test(tc1_1, s21_fmod9);
  tcase_add_test(tc1_1, s21_exp1);
  tcase_add_test(tc1_1, s21_exp2);
  tcase_add_test(tc1_1, s21_exp3);
  tcase_add_test(tc1_1, s21_exp4);
  tcase_add_test(tc1_1, s21_exp5);
  tcase_add_test(tc1_1, s21_exp6);
  tcase_add_test(tc1_1, s21_exp7);
  tcase_add_test(tc1_1, s21_exp8);
  tcase_add_test(tc1_1, s21_exp9);
  tcase_add_test(tc1_1, s21_exp10);
  tcase_add_test(tc1_1, s21_exp11);
  tcase_add_test(tc1_1, s21_exp12);
  tcase_add_test(tc1_1, s21_pow1);
  tcase_add_test(tc1_1, s21_pow2);
  tcase_add_test(tc1_1, s21_pow3);
  tcase_add_test(tc1_1, s21_pow4);
  tcase_add_test(tc1_1, s21_pow5);
  tcase_add_test(tc1_1, s21_pow6);
  tcase_add_test(tc1_1, s21_pow7);
  tcase_add_test(tc1_1, s21_pow8);
  tcase_add_test(tc1_1, s21_pow9);
  tcase_add_test(tc1_1, s21_pow10);
  tcase_add_test(tc1_1, s21_pow11);
  tcase_add_test(tc1_1, s21_pow12);
  tcase_add_test(tc1_1, s21_pow13);
  tcase_add_test(tc1_1, s21_log1);
  tcase_add_test(tc1_1, s21_log2);
  tcase_add_test(tc1_1, s21_log3);
  tcase_add_test(tc1_1, s21_log4);
  tcase_add_test(tc1_1, s21_log5);
  tcase_add_test(tc1_1, s21_log6);
  tcase_add_test(tc1_1, s21_log7);
  tcase_add_test(tc1_1, s21_log8);
  tcase_add_test(tc1_1, s21_log9);
  tcase_add_test(tc1_1, s21_log10);
  tcase_add_test(tc1_1, s21_log11);
  tcase_add_test(tc1_1, s21_log12);
  tcase_add_test(tc1_1, s21_log13);
  tcase_add_test(tc1_1, s21_sqrt1);
  tcase_add_test(tc1_1, s21_sqrt2);
  tcase_add_test(tc1_1, s21_sqrt3);
  tcase_add_test(tc1_1, s21_sqrt4);
  tcase_add_test(tc1_1, s21_sqrt5);
  tcase_add_test(tc1_1, s21_sqrt6);
  tcase_add_test(tc1_1, s21_sqrt7);
  tcase_add_test(tc1_1, s21_sqrt8);
  tcase_add_test(tc1_1, s21_sqrt9);
  tcase_add_test(tc1_1, s21_sqrt10);
  tcase_add_test(tc1_1, s21_sqrt11);
  tcase_add_test(tc1_1, s21_sqrt12);
  tcase_add_test(tc1_1, s21_sqrt13);
  tcase_add_test(tc1_1, s21_sin1);
  tcase_add_test(tc1_1, s21_sin2);
  tcase_add_test(tc1_1, s21_sin3);
  tcase_add_test(tc1_1, s21_sin4);
  tcase_add_test(tc1_1, s21_sin5);
  tcase_add_test(tc1_1, s21_sin6);
  tcase_add_test(tc1_1, s21_sin7);
  tcase_add_test(tc1_1, s21_sin8);
  tcase_add_test(tc1_1, s21_cos1);
  tcase_add_test(tc1_1, s21_cos2);
  tcase_add_test(tc1_1, s21_cos3);
  tcase_add_test(tc1_1, s21_cos4);
  tcase_add_test(tc1_1, s21_cos5);
  tcase_add_test(tc1_1, s21_cos6);
  tcase_add_test(tc1_1, s21_cos7);
  tcase_add_test(tc1_1, s21_cos8);
  tcase_add_test(tc1_1, s21_cos9);
  tcase_add_test(tc1_1, s21_cos10);
  tcase_add_test(tc1_1, s21_cos11);
  tcase_add_test(tc1_1, s21_tan1);
  tcase_add_test(tc1_1, s21_tan2);
  tcase_add_test(tc1_1, s21_tan3);
  tcase_add_test(tc1_1, s21_tan4);
  tcase_add_test(tc1_1, s21_tan5);
  tcase_add_test(tc1_1, s21_tan6);
  tcase_add_test(tc1_1, s21_tan7);
  tcase_add_test(tc1_1, s21_tan8);
  tcase_add_test(tc1_1, s21_tan9);
  tcase_add_test(tc1_1, s21_tan10);
  tcase_add_test(tc1_1, s21_tan11);
  tcase_add_test(tc1_1, s21_tan12);
  tcase_add_test(tc1_1, s21_tan13);
  tcase_add_test(tc1_1, s21_tan14);
  tcase_add_test(tc1_1, s21_asin1);
  tcase_add_test(tc1_1, s21_asin2);
  tcase_add_test(tc1_1, s21_asin3);
  tcase_add_test(tc1_1, s21_asin4);
  tcase_add_test(tc1_1, s21_asin5);
  tcase_add_test(tc1_1, s21_asin6);
  tcase_add_test(tc1_1, s21_asin7);
  tcase_add_test(tc1_1, s21_asin8);
  tcase_add_test(tc1_1, s21_asin9);
  tcase_add_test(tc1_1, s21_asin10);
  tcase_add_test(tc1_1, s21_acos1);
  tcase_add_test(tc1_1, s21_acos2);
  tcase_add_test(tc1_1, s21_acos3);
  tcase_add_test(tc1_1, s21_acos4);
  tcase_add_test(tc1_1, s21_acos5);
  tcase_add_test(tc1_1, s21_acos6);
  tcase_add_test(tc1_1, s21_acos7);
  tcase_add_test(tc1_1, s21_acos8);
  tcase_add_test(tc1_1, s21_acos9);
  tcase_add_test(tc1_1, s21_atan1);
  tcase_add_test(tc1_1, s21_atan2);
  tcase_add_test(tc1_1, s21_atan3);
  tcase_add_test(tc1_1, s21_atan4);
  tcase_add_test(tc1_1, s21_atan5);
  tcase_add_test(tc1_1, s21_atan6);
  tcase_add_test(tc1_1, s21_atan7);
  tcase_add_test(tc1_1, s21_atan8);
  tcase_add_test(tc1_1, s21_atan9);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
