#!/bin/bash

init() {
  export var1="HOSTNAME = $HOSTNAME"
  export var2="TIMEZONE = $(cat /etc/timezone)"
  export var3="USER = $USER"
  export var4="OS = $OSTYPE"
  export var5="DATE = $(date +%d) $(date +%b) $(date +%Y) $(date +%H:%M:%S)"
  export var6="UPTIME = $(uptime -p)"
  export var7="UPTIME_SEC = $(awk '{print $1}' /proc/uptime)"
  export var8="IP = $(hostname -I)"
  export var9="MASK = $(ifconfig | grep netmask | sed -n 1p | awk '{print $4}')"
  export var10="GATEWAY = $(ip r | grep default | awk '{print $3}')"
  export var11="RAM_TOTAL = `echo "scale=3; $(free -m | grep Mem | awk '{print $2}') / 1024.0" | bc` GB"
  export var12="RAM_USED = `echo "scale=3; $(free -m | grep Mem | awk '{print $3}') / 1024.0" | bc` GB"
  export var13="RAM_FREE = `echo "scale=3; $(free -m | grep Mem | awk '{print $4}') / 1024.0" | bc` GB"
  export var14="SPACE_ROOT = `echo "scale=2; $(df / | grep dev  | awk '{print $2}') / 1024.0" | bc` MB"
  export var15="SPACE_ROOT_USED = `echo "scale=2; $(df / | grep dev | awk '{print $3}') / 1024.0" | bc` MB"
  export var16="SPACE_ROOT_FREE = `echo "scale=2; $(df / | grep dev | awk '{print $4}') / 1024.0" | bc` MB"
}

print_all() {
  echo "$var1"
  echo "$var2"
  echo "$var3"
  echo "$var4"
  echo "$var5"
  echo "$var6"
  echo "$var7"
  echo "$var8"
  echo "$var9"
  echo "$var10"
  echo "$var11"
  echo "$var12"
  echo "$var13"
  echo "$var14"
  echo "$var15"
  echo "$var16"
}

save_data() {
  read -p "Need save file [Y/N]: " 
	if [ $REPLY == "y" ] || [ $REPLY == "Y" ]; then
	  print_all >> $(date +%d_%m_%Y_%H_%M_%S).status
	fi
}