#!/bin/bash

print_all() {
	echo "Total number of folders (including all nested ones) = $(find $1 -type d 2>/dev/null | wc -l)"
	echo "Top 5 folders of maximum size arranged in descending order (path and size):"
	top_5_folders_max $1
	echo "Total number of files = $(find $1 -type f 2>/dev/null | wc -l)"
	echo "Number of:"
	echo "Configuration files (with the .conf extension) = $(find $1 -name *.conf -type f 2>/dev/null | wc -l)"
	echo "Text files: $(find $1 -name *.txt -type f 2>/dev/null | wc -l)"
	echo "Executable files = $(find $1 -type f -perm /u=x,g=x,o=x 2>/dev/null | wc -l)"
	echo "Log files (with the extension .log) = $(find $1 -name *.log -type f 2>/dev/null | wc -l)"
	echo "Archive files = $(quanity_archive_files $1)"
	echo "Symbolic links = $(find /var/log/ -type l 2>/dev/null | wc -l)"
	echo "TOP 10 files of maximum size arranged in descending order (path, size and type):"
	top_10_files_max $1
	echo "TOP 10 executable files of the maximum size arranged in descending order (path, size and MD5 hash of file):"
	top_10_executable_files_max $1
	echo "Script execution time (in seconds) = $SECONDS"
}

quanity_archive_files() {
	local f1=$(find $1 -name *.tar -type f 2>/dev/null | wc -l)
	local f2=$(find $1 -name *.gz -type f 2>/dev/null | wc -l)
	local f3=$(find $1 -name *.bz2 -type f 2>/dev/null | wc -l)
	local f4=$(find $1 -name *.zip -type f 2>/dev/null | wc -l)
	local f5=$(find $1 -name *.7z -type f 2>/dev/null | wc -l)
	echo "$(( $f1 + $f2 + $f3 + $f4 + $f5 ))"
}

top_5_folders_max() {
	for (( i=1; i < 6; i++ ))
		do
		local var1="$(du -h $1 2>/dev/null | sort -rh | sed -n ${i}p | awk '{print $2}')"
		local var2="$(du -h $1 2>/dev/null | sort -rh | sed -n ${i}p | awk '{print $1}')"
		if [ ! -z $var1 ];then
			echo "$i - $var1, $var2"
		elif [ $i == 1 ];then
			echo "No files"
			break
		else
			break
		fi
	done
}

top_10_files_max() {
	for (( i=1; i < 11; i++ ))
		do
		local var1="$(find $1 -type f -exec du -h {} + 2>/dev/null | sort -rh | sed -n ${i}p |awk '{print $2}')"
		local var2="$(find $1 -type f -exec du -h {} + 2>/dev/null | sort -rh | sed -n ${i}p |awk '{print $1}')"
		if [ ! -z $var1 ];then
			local var3="${var1##*.}"
			echo "$i - $var1, $var2, $var3"
		elif [ $i == 1 ];then
			echo "No files"
			break
		else
			break
		fi
	done
}

top_10_executable_files_max() {
	for (( i=1; i < 11; i++ ))
		do
		local var1="$(find $1 -type f -perm /u=x,g=x,o=x -exec du -h {} + 2>/dev/null | sort -nr | sed -n ${i}p | awk '{print $2}')"
		local var2="$(find $1 -type f -perm /u=x,g=x,o=x -exec du -h {} + 2>/dev/null | sort -nr | sed -n ${i}p | awk '{print $1}')"
		if [ -x "$var1" ]; then
			local sha_sum=$(sha256sum "$var1" | awk '{print $1}')
			echo "$i - $var1 $var2 $sha_sum"
		elif [ $i == 1 ];then
			echo "No files"
			break
		else 
			break
		fi
	done
}

