#!/bin/bash

check_input() {
  if [ ! $# -eq 1 ]; then
    echo "Wrong input!"
    exit 1
  elif [[ ! $1 =~ ^[1-4]{1}$ ]]; then
    echo "Wrong input parametr!"
    exit 1
  elif [ ! -d ../04/logs ]; then  
    cd ../04 && ./main.sh && cd ../05
  fi
  echo "Start script"
}

mode() {
  if [ $1 == 1 ]; then
    first_task
  elif [ $1 == 2 ]; then
    second_task
  elif [ $1 == 3 ]; then
    third_task
  elif [ $1 == 4 ]; then
    fourth_task
  fi
}

first_task() {
codes=("503" "502" "501" "500" "404" "403" "401" "400" "201" "200")
  for((i=0; i < 10; i++)); do
    awk -v code="${codes[$i]}" '$9==code' ../04/logs/access{1..5}.log
  done
}

second_task() {
  awk '!U[$1]++ {print $1}' ../04/logs/access{1..5}.log
}

third_task() {
  awk '$9 >= 400, $9 <= 600 {print $0}' ../04/logs/access{1..5}.log
}

fourth_task() {
  awk '!U[$1]++ && $9 >= 400, $9 <= 600 {print $0}' ../04/logs/access{1..5}.log
}